name: Sync Labels
on:
    workflow_dispatch:
    push:
        branches: [main, feature/label-create-yml]
jobs:
  sync-labels:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manifest: .github/labels.yml
